# This file is automatically generated. Do not edit.
# generated by https://github.com/jonhillmtl/pyobjcidl.git

import objc, ctypes, re
import datetime
NSObject = objc.lookUpClass("NSObject")

class POExample(NSObject):

    pass

def main():
    test_POExample = POExample.alloc().init()
    print test_POExample

if __name__ == "__main__":
    main()