# This file is automatically generated. Do not edit.
# generated by https://github.com/jonhillmtl/pyobjcidl.git
import objc, ctypes, re
import datetime
NSObject = objc.lookUpClass("NSObject")
class POMember(NSObject):
    
    simple = 0

    pass

def main():
    test_POMember = POMember.alloc().init()
    print test_POMember

if __name__ == "__main__":
    main()