# This file is automatically generated. Do not edit.
# generated by https://github.com/jonhillmtl/pyobjcidl.git
class POMember:
    
    simple = 0

    pass

def main():
    print 'valid'
    
if __name__ == "__main__":
    main()