# This file is automatically generated. Do not edit.
# generated by https://github.com/jonhillmtl/pyobjcidl.git

class POSimple:
    simple = ''
    index = ''


    def simple_func(self, test):
        pass

