# This file is automatically generated. Do not edit.
# generated by https://github.com/jonhillmtl/pyobjcidl.git


class POSimple:
    
    simple_int = 0


    simple_string = ''


    simple_dict = {}


    simple_mutable_dict = {}


    simple_array = []


    simple_mutable_array = []


    simple_boolean = False



    def simple_func(self, test):
        pass


    pass


def main():
    print 'valid'
    
if __name__ == "__main__":
    main()