# This file is automatically generated. Do not edit.
# generated by https://github.com/jonhillmtl/pyobjcidl.git


class POExample1:


    def text1(self, test1):
        pass


    pass

class POExample2:




    pass
