
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'k\x91FS\xe2j;\xb9\x01U\x1fp\x88\x9d\xc5x'
    
_lr_action_items = {'FUNCTION':([6,7,10,13,14,16,17,18,23,37,],[-17,-18,15,-10,-19,15,-16,-15,-11,-8,]),'RPAREN':([28,31,34,35,36,],[33,-3,-2,-1,-4,]),'STRING':([6,7,10,14,15,17,18,27,32,],[8,-18,8,-19,20,-16,-15,29,29,]),'SEMICOLON':([11,12,24,33,],[17,18,26,37,]),'RCURLY':([6,7,10,13,14,16,17,18,23,37,],[-17,-18,-9,-10,-19,24,-16,-15,-11,-8,]),'INT':([6,7,10,14,15,17,18,27,32,],[9,-18,9,-19,21,-16,-15,30,30,]),'VOID':([15,],[22,]),'CLASS':([0,1,2,4,26,],[3,3,-13,-14,-12,]),'LCURLY':([5,],[6,]),'COMMA':([28,31,34,35,36,],[32,-3,-2,-1,-4,]),'LPAREN':([25,],[27,]),'ID':([3,8,9,19,20,21,22,29,30,],[5,11,12,25,-6,-5,-7,34,35,]),'$end':([1,2,4,26,],[0,-13,-14,-12,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'function':([10,16,],[13,23,]),'member':([6,10,],[7,14,]),'return':([15,],[19,]),'argumentlist':([27,],[28,]),'classlist':([0,],[1,]),'argument':([27,32,],[31,36,]),'memberlist':([6,],[10,]),'functionlist':([10,],[16,]),'class':([0,1,],[2,4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> classlist","S'",1,None,None,None),
  ('argument -> INT ID','argument',2,'p_argument_expr','/Users/jon/dev/pyobjcidl/plyer.py',93),
  ('argument -> STRING ID','argument',2,'p_argument_expr','/Users/jon/dev/pyobjcidl/plyer.py',94),
  ('argumentlist -> argument','argumentlist',1,'p_argumentlist_expr','/Users/jon/dev/pyobjcidl/plyer.py',101),
  ('argumentlist -> argumentlist COMMA argument','argumentlist',3,'p_argumentlist_expr','/Users/jon/dev/pyobjcidl/plyer.py',102),
  ('return -> INT','return',1,'p_return','/Users/jon/dev/pyobjcidl/plyer.py',106),
  ('return -> STRING','return',1,'p_return','/Users/jon/dev/pyobjcidl/plyer.py',107),
  ('return -> VOID','return',1,'p_return','/Users/jon/dev/pyobjcidl/plyer.py',108),
  ('function -> FUNCTION return ID LPAREN argumentlist RPAREN SEMICOLON','function',7,'p_function_expr','/Users/jon/dev/pyobjcidl/plyer.py',112),
  ('functionlist -> <empty>','functionlist',0,'p_functionlist_expr','/Users/jon/dev/pyobjcidl/plyer.py',120),
  ('functionlist -> function','functionlist',1,'p_functionlist_expr','/Users/jon/dev/pyobjcidl/plyer.py',121),
  ('functionlist -> functionlist function','functionlist',2,'p_functionlist_expr','/Users/jon/dev/pyobjcidl/plyer.py',122),
  ('class -> CLASS ID LCURLY memberlist functionlist RCURLY SEMICOLON','class',7,'p_class_expr','/Users/jon/dev/pyobjcidl/plyer.py',126),
  ('classlist -> class','classlist',1,'p_classlist_expr','/Users/jon/dev/pyobjcidl/plyer.py',136),
  ('classlist -> classlist class','classlist',2,'p_classlist_expr','/Users/jon/dev/pyobjcidl/plyer.py',137),
  ('member -> INT ID SEMICOLON','member',3,'p_member_expr','/Users/jon/dev/pyobjcidl/plyer.py',141),
  ('member -> STRING ID SEMICOLON','member',3,'p_member_expr','/Users/jon/dev/pyobjcidl/plyer.py',142),
  ('memberlist -> <empty>','memberlist',0,'p_memberlist_expr','/Users/jon/dev/pyobjcidl/plyer.py',149),
  ('memberlist -> member','memberlist',1,'p_memberlist_expr','/Users/jon/dev/pyobjcidl/plyer.py',150),
  ('memberlist -> memberlist member','memberlist',2,'p_memberlist_expr','/Users/jon/dev/pyobjcidl/plyer.py',151),
]
